# Generated by Django 4.1.7 on 2023-04-03 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('clientname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('registrationtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_registration_table',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('2-Wheeler', '2-Wheeler'), ('4-Wheeler', '4-Wheeler'), ('Trucks', 'Trucks')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('price', models.PositiveIntegerField()),
                ('hours', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(48)])),
                ('image', models.FileField(upload_to='vehicleimages')),
            ],
            options={
                'db_table': 'vehicle_table',
            },
        ),
    ]
